AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template for leo cloudwatch dashboard'
Parameters:
# Tag Parameters on every resource.
  environment:
    Type: String
    # Default: dev1
  accountId:
    Type: String
    # Default: XXXXXXXXX  
  awsRegion:
    Type: String
    # Default: us-east-1
  dbInstanceName:
    Type: String
    # Default: acqldysvc- clu-leodev1/acqldysvc_dev1  
  leoReqSqs:
    Type: String
    # Default: acqldysvc-dev1-sfbu-LEOREQ-dev-v1
  leoResSqs:
    Type: String
    # Default: acqldysvc-dev1-sfbu-loaneligibilityresponse-dev1-v1
  loanAcquisitionsEligibilityRequestedSns:
    Type: String
    # Default: acqldysvc-dev1-sfbu-LoanAcquisitionsEligibilityRequested-dev1-v1
  loanPricingEligibilityRequestedSns:
    Type: String
    # Default: acqldysvc-dev1-sfbu-LoanPricingEligibilityRequested-dev1-v1
  leoResSnsn:
    Type: String
    # Default: acqldysvc-dev1-sfbu-LEORES-dev1-v1

Resources:
  leoCWDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub leo-${environment}-Dashboard
      DashboardBody: !Sub '{"widgets": [
        {
            "height": 6,
            "width": 6,
            "y": 0,
            "x": 0,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/RDS", "CPUUtilization", "DBInstanceIdentifier", "${dbInstanceName}", { "stat": "Average", "id": "m0", "region": "${awsRegion}" } ]
                ],
                "legend": {
                    "position": "bottom"
                },
                "period": 300,
                "view": "timeSeries",
                "stacked": false,
                "start": "-PT3H",
                "end": "P0D",
                "title": "${dbInstanceName}-RDS-CPUUtilization",
                "region": "${awsRegion}"
            }
        },
        {
            "height": 6,
            "width": 6,
            "y": 0,
            "x": 6,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/RDS", "DatabaseConnections", "DBInstanceIdentifier", "${dbInstanceName}", { "stat": "Sum", "id": "m0" } ]
                ],
                "legend": {
                    "position": "bottom"
                },
                "period": 300,
                "view": "timeSeries",
                "stacked": false,
                "start": "-PT3H",
                "end": "P0D",
                "title": "${dbInstanceName}-RDS-DatabaseConnections",
                "region": "${awsRegion}"
            }
        },
        {
            "height": 6,
            "width": 6,
            "y": 0,
            "x": 12,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/RDS", "FreeableMemory", "DBInstanceIdentifier", "${dbInstanceName}", { "stat": "Average", "id": "m0" } ]
                ],
                "legend": {
                    "position": "bottom"
                },
                "period": 300,
                "view": "timeSeries",
                "stacked": false,
                "start": "-PT3H",
                "end": "P0D",
                "title": "${dbInstanceName}-RDS-FreeableMemory",
                "region": "${awsRegion}"
            }
        },
        {
            "height": 6,
            "width": 6,
            "y": 0,
            "x": 18,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/RDS", "ReadThroughput", "DBInstanceIdentifier", "${dbInstanceName}", { "stat": "Average", "id": "m0", "region": "${awsRegion}" } ]
                ],
                "legend": {
                    "position": "bottom"
                },
                "period": 300,
                "view": "timeSeries",
                "stacked": false,
                "start": "-PT3H",
                "end": "P0D",
                "title": "${dbInstanceName}-RDS-ReadThroughput",
                "region": "${awsRegion}"
            }
        },
        {
            "height": 6,
            "width": 6,
            "y": 6,
            "x": 0,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/RDS", "WriteThroughput", "DBInstanceIdentifier", "${dbInstanceName}", { "stat": "Average", "id": "m0", "region": "${awsRegion}" } ]
                ],
                "legend": {
                    "position": "bottom"
                },
                "period": 300,
                "view": "timeSeries",
                "stacked": false,
                "start": "-PT3H",
                "end": "P0D",
                "title": "${dbInstanceName}-RDS-WriteThroughput",
                "region": "${awsRegion}"
            }
        },
        {
            "height": 6,
            "width": 6,
            "y": 6,
            "x": 6,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/SQS","ApproximateAgeOfOldestMessage", "Name", "${leoReqSqs}", { "stat": "Average", "region": "${awsRegion}" }],
                    [".", "NumberOfMessagesSent", ".", ".", { "stat": "Average", "region": "${awsRegion}" }],
                    [".", "SentMessageSize", ".", ".", { "stat": "Average", "region": "${awsRegion}" }] 
                ],
                "legend": {
                    "position": "bottom"
                },
                "period": 300,
                "view": "timeSeries",
                "stacked": false,
                "start": "-PT3H",
                "title": "${leoReqSqs}",
                "region": "${awsRegion}"
            }
        },
        {
            "height": 6,
            "width": 6,
            "y": 6,
            "x": 12,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/SQS","ApproximateAgeOfOldestMessage", "Name", "${leoResSqs}", { "stat": "Average", "region": "${awsRegion}" }],
                    [".", "NumberOfMessagesSent", ".", ".", { "stat": "Average", "region": "${awsRegion}" }],
                    [".", "SentMessageSize", ".", ".", { "stat": "Average", "region": "${awsRegion}" }] 
                ],
                "legend": {
                    "position": "bottom"
                },
                "period": 300,
                "view": "timeSeries",
                "stacked": false,
                "start": "-PT3H",
                "title": "${leoResSqs}",
                "region": "${awsRegion}"
            }
        },
        {
            "height": 6,
            "width": 6,
            "y": 6,
            "x": 18,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/SNS", "NumberOfMessagesPublished", "Name", "${loanAcquisitionsEligibilityRequestedSns}",{ "stat": "Sum", "region": "${awsRegion}" }],
                    [".", "NumberOfNotificationsFailed", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }],
                    [".", "NumberOfNotificationsRedrivenToDlq", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }],
                    [".", "NumberOfNotificationsFailedToRedriveToDlq", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }],
                    [".", "PublishSize", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }]                                                                      
                ],
                "legend": {
                    "position": "bottom"
                },
                "period": 300,
                "view": "timeSeries",
                "stacked": false,
                "start": "-PT3H",
                "title": "${loanAcquisitionsEligibilityRequestedSns}",
                "region": "${awsRegion}"
            }
        },
        {
            "height": 6,
            "width": 6,
            "y": 12,
            "x": 0,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/SNS", "NumberOfMessagesPublished", "Name", "${loanPricingEligibilityRequestedSns}", { "stat": "Sum", "region": "${awsRegion}" }],
                    [".", "NumberOfNotificationsFailed", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }],
                    [".", "NumberOfNotificationsRedrivenToDlq", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }],
                    [".", "NumberOfNotificationsFailedToRedriveToDlq", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }],
                    [".", "PublishSize", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }]                                                                      
                ],
                "legend": {
                    "position": "bottom"
                },
                "period": 300,
                "view": "timeSeries",
                "stacked": false,
                "start": "-PT3H",
                "title": "${loanPricingEligibilityRequestedSns}",
                "region": "${awsRegion}"
            }
        },
        {
            "height": 6,
            "width": 6,
            "y": 12,
            "x": 6,
            "type": "metric",
            "properties": {
                "metrics": [
                    [ "AWS/SNS", "NumberOfMessagesPublished", "Name", "${leoResSnsn}", { "stat": "Sum", "region": "${awsRegion}" }],
                    [".", "NumberOfNotificationsFailed", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }],
                    [".", "NumberOfNotificationsRedrivenToDlq", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }],
                    [".", "NumberOfNotificationsFailedToRedriveToDlq", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }],
                    [".", "PublishSize", ".", ".",{ "stat": "Average", "region": "${awsRegion}" }]                                                                      
                ],
                "legend": {
                    "position": "bottom"
                },
                "period": 300,
                "view": "timeSeries",
                "stacked": false,
                "start": "-PT3H",
                "title": "${leoResSnsn}",
                "region": "${awsRegion}"
            }
        }
]
}'
